# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml

image:
  repository: witcherek7/goke
  pullPolicy: Always

automountServiceAccountToken: true

args:
- -m
- gin

service:
  main:
    ports:
      http:
        port: 3000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

