version: 3

tasks:
  dapr:
    deps:
    - :tools:dapr:local
    - :app:build
    cmds:
    # - task: :app:build
    - >
      dapr run --app-id goke 
      --dapr-http-port 3500 --app-port 3000 --app-protocol http
      --components-path chart/templates/dapr-components
      -- app/goke dapr
    preconditions:
      - test -f app/goke

  dapr:get:secret: curl http://localhost:3500/v1.0/secrets/goke/secret 

  curl:subscriptions: curl http://localhost:3000/dapr/subscribe | jq
  curl:publish: echo "fun" | curl -X POST http://localhost:3000/queue/publish
  http:subscriptions: http http://localhost:3000/dapr/subscribe | jq
  http:publish: echo "fun" | http POST http://localhost:3000/queue/publish
  http:subscribe: http http://localhost:3000/queue/subscribe
  http:store: echo -n "store this 1" | http http://localhost:3000/store/key1
  http:retrieve: http http://localhost:3000/retrieve/key1