version: 3

tasks:
  gum:install:
  - |
    echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list
    sudo apt update && sudo apt install gum

  go:install:
  - sudo apt install -y golang-go

  go:install:advanced:
  - wget -nc https://go.dev/dl/go1.18.5.linux-amd64.tar.gz
  - defer: rm go1.18.5.linux-amd64.tar.gz
  - sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz
  - >
    gum style 'export PATH=$PATH:/usr/local/go/bin'
    --foreground 212 --border-foreground 212 --border double
    --align center --width 50 --margin "1 2" --padding "2 4"

  go:init:
    dir: app
    cmds:
    - go mod init goke

  go:env:
    dir: app
    cmds:
    - go env

  go:requirements:
    dir: app
    cmds:
    - go mod tidy

  app:install:
    dir: app
    cmds:
    - go install

  app:run:local:
    dir: app
    cmds:
    - go run main.go

  go:delete-downlaoded-modules:
  - go clean -modcache

  pre-commit:install:
  - pip install pre-commit

  pre-commit:install-hooks:
  - pre-commit install
  - pre-commit install -t commit-msg

  pre-commit:run-hooks:
  - pre-commit run --all-files

  git:commit:
    vars:
      TYPE:
        sh: gum choose feat fix docs
      SCOPE:
        sh: gum input --placeholder "Scope"
      MESSAGE:
        sh: gum input --placeholder "Message"
    cmds:
    - git add .
    - >
      git commit -m "{{ .TYPE }}({{ .SCOPE }}): {{ .MESSAGE }}"
    - git push origin main
