version: 3

includes:
  git: modules/git.yaml
  dev: modules/dev.yaml
  tools: modules/tools.yaml
  app: 
    taskfile: app/Taskfile.yaml
    dir: app
  k3d:
    taskfile: vendir/k3d/Taskfile.yaml
    dir: vendir/k3d
    vars:
      CLUSTER_NAME: goke
  tests:
    dir: tests 
    taskfile: tests/Taskfile.yaml

tasks:
  default: 
  - task -a | grep "{{ .CLI_ARGS }}"

  dev:helm:
  - task: k3d:create
  - task: tilt:start:helm
  - defer: 
      task: k3d:delete

  dev:compose:
  - task: tilt:start:compose

  tilt:start:compose: tilt up -f tiltfiles/Tiltfile.compose
  tilt:start:helm: tilt up -f tiltfiles/Tiltfile.helm

  gum:install:
  - |
    echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list
    sudo apt update && sudo apt install gum

  go:install:
  - sudo apt install -y golang-go

  go:install:advanced:
  - wget -nc https://go.dev/dl/go1.18.5.linux-amd64.tar.gz
  - defer: rm go1.18.5.linux-amd64.tar.gz
  - sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz
  - >
    gum style 'export PATH=$PATH:/usr/local/go/bin'
    --foreground 212 --border-foreground 212 --border double
    --align center --width 50 --margin "1 2" --padding "2 4"



  sync:
  - vendir sync

