name: goke
apiVersion: v2
appVersion: 0.0.1-dev
version: 0.0.1
maintainers:
- name: Krzysztof Wiatrzyk
  email: krzwiatrzyk@protonmail.com
- name: Maciej Kolodziejczyk
sources:
- https://github.com/krzwiatrzyk/goke
keywords:
  - "goke"
  - "example"
  - "golang"
annotations:
kubeVersion: ">1.23.0-0"
icon: data:image/svg+xml;utf8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0Ny41IDQ3LjUiPjxkZWZzPjxjbGlwUGF0aCBpZD0iYSI+PHBhdGggZD0iTTAgMzhoMzhWMEgwdjM4WiIvPjwvY2xpcFBhdGg+PC9kZWZzPjxnIGNsaXAtcGF0aD0idXJsKCNhKSIgdHJhbnNmb3JtPSJtYXRyaXgoMS4yNSAwIDAgLTEuMjUgMCA0Ny41KSI+PHBhdGggZmlsbD0iIzU1YWNlZSIgZD0iTTE3Ljc4NCAyMi45OThjLjM3NC4xMS43NTguMTY2IDEuMTQzLjE2NmE0LjA2MyA0LjA2MyAwIDAgMCAzLjg3NS0yLjkwMSA0LjA1IDQuMDUgMCAwIDAtMy44NzktNS4xODYgNC4wNjMgNC4wNjMgMCAwIDAtMy44NzUgMi45MDIgNC4wNDYgNC4wNDYgMCAwIDAgMi43MzYgNS4wMTltMTguOTk4LTEwLjUxNWMtLjEzLjQzNy0uNDIyLjc5OS0uODIxIDEuMDE1LS44MDIuNDM2LTEuODc5LjExNy0yLjMxNy0uNjgyYTEzLjk3MiAxMy45NzIgMCAwIDAtOC4zNzItNi43NTcgMTQuMDkzIDE0LjA5MyAwIDAgMC0xMC42OTcgMS4xNDQgMTAuODI0IDEwLjgyNCAwIDAgMC01LjI0MiA2LjQ5M2MtLjc0IDIuNTEzLS40OTUgNS4wMTYuNTUyIDcuMDMyYTkuNzM1IDkuNzM1IDAgMCAxIC4xNjQtNC45MDcgOS42OTkgOS42OTkgMCAwIDEgNC43MDEtNS44MjMgMTEuODM0IDExLjgzNCAwIDAgMSA4Ljk3OC0uOTYxIDExLjcxNCAxMS43MTQgMCAwIDEgNy4wMjcgNS42NzEgMTQuMjE4IDE0LjIxOCAwIDAgMSAxLjE2NSAxMC44OTggMTQuMjI4IDE0LjIyOCAwIDAgMS02Ljg4MyA4LjUyOSAxNy41NCAxNy41NCAwIDAgMS0xMy4yOTkgMS40MiAxNy4zNjEgMTcuMzYxIDAgMCAxLTEwLjQwNy04LjM5OCAxLjcxIDEuNzEgMCAwIDEgLjY4Mi0yLjMxN2MuODAzLS40NCAxLjg4My0uMTE3IDIuMzE5LjY4MmExMy45NTkgMTMuOTU5IDAgMCAwIDguMzcxIDYuNzU1IDE0LjExMSAxNC4xMTEgMCAwIDAgMTAuNjk5LTEuMTQyIDEwLjgzIDEwLjgzIDAgMCAwIDUuMjM5LTYuNDk1Yy43NDItMi41MTQuNDk3LTUuMDE3LS41NTEtNy4wMzNhOS43NjMgOS43NjMgMCAwIDEtLjE2MiA0LjkxMSA5LjczMyA5LjczMyAwIDAgMS00LjcwMyA1LjgyMyAxMS44NTIgMTEuODUyIDAgMCAxLTguOTguOTU5IDExLjcxMyAxMS43MTMgMCAwIDEtNy4wMjUtNS42NzEgMTQuMjE0IDE0LjIxNCAwIDAgMS0xLjE2NS0xMC44OTcgMTQuMjIgMTQuMjIgMCAwIDEgNi44ODMtOC41MjkgMTcuNDcgMTcuNDcgMCAwIDEgOC4zNDEtMi4xNDFjMS42NjkgMCAzLjMzNy4yNDIgNC45NTguNzJhMTcuMzUgMTcuMzUgMCAwIDEgMTAuNDA2IDguMzk4Yy4yMTkuNDAxLjI2OS44NjQuMTM5IDEuMzAzIi8+PC9nPjwvc3ZnPg==
dependencies:
- name: common
  version: "4.5.x"
  repository: https://library-charts.k8s-at-home.com