version: 3

tasks:
  test:
  - go test -v ./...

  cobra:install:
    cmds:
    - go install github.com/spf13/cobra-cli
    status:
    - command -v cobra-cli

  cobra:init:
  - cobra-cli init --author "Krzysztof Wiatrzyk" --viper --license "Apache 2.0"

  cobra:add:command:
    deps:
    - cobra:install
    cmds:
    - cobra-cli add {{ .CLI_ARGS }}

  build:image:
  - docker image build . -t goke:0.0.1-dev

  push:image:
  - docker tag goke:0.0.1-dev witcherek7/goke:0.0.1-dev
  - docker push witcherek7/goke:0.0.1-dev

  run:local:
    cmds:
    - go run main.go run

  run:container:
  - docker container run -p 3000:3000 --rm goke:0.0.1-dev run -m http

  init:
    cmds:
    - go mod init goke

  env:
    cmds:
    - go env

  requirements:
    cmds:
    - go mod tidy

  install:
    cmds:
    - go install
    
  build:
    cmds:
    - go build .
    sources:
    - cmd/*
    - modules/**/*
    generates:
    - goke

  delete-downlaoded-modules:
  - go clean -modcache

  ginkgo:install:
  - go get github.com/onsi/ginkgo/v2/ginkgo
  - go get github.com/onsi/gomega/...
  - go install github.com/onsi/ginkgo/v2/ginkgo

  ginkgo:bootstrap:wallet:
    dir: modules/wallet
    cmds:
    - ginkgo bootstrap
    - ginkgo generate movie
    - ginkgo generate wallet
    - ginkgo generate account

  ginkgo:test:wallet:
    dir: modules/wallet
    cmds:
    - ginkgo