version: 3

tasks:
  test:
  - go test -v ./...

  cobra:install:
  - go install github.com/spf13/cobra-cli

  cobra:init:
  - cobra-cli init --author "Krzysztof Wiatrzyk" --viper --license "Apache 2.0"

  cobra:add:command:
  - cobra-cli add {{ .CLI_ARGS }}

  run:
  - go run main.go run

  build:image:
  - docker image build . -t goke:0.0.1-dev

  push:image:
  - docker tag goke:0.0.1-dev witcherek7/goke:0.0.1-dev
  - docker push witcherek7/goke:0.0.1-dev

  run:container:
  - docker container run -p 3000:3000 --rm goke:0.0.1-dev run -m http
