version: 3

tasks:
  install:
    cmds:
    - curl https://get.okteto.com -sSfL | sh
    status:
    - command -v okteto
  
  up: okteto up
  down: okteto destroy 
  deploy: okteto deploy
  build: okteto build

  test: http https://goke-krzwiatrzyk.cloud.okteto.net/ping