{{ if .Values.extensions.dapr }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
{{ end }}