version: 3

vars:
  INSTALLER: apt

tasks:
  install:cli:
    cmds:
    - sudo {{ .INSTALLER }} install -y httpie
    status:
    - command -v http

  install:ui:
    deps:
    - install:appimagelauncher
    cmds:
    - wget -nc https://github.com/httpie/desktop/releases/download/v2022.15.1/HTTPie-2022.15.1.AppImage -O httpie.AppImage
    - AppImageLauncher httpie.AppImage
    status:
    - ls ${HOME}/Applications | grep httpie

  install:appimagelauncher:
    cmds:
    - sudo add-apt-repository ppa:appimagelauncher-team/stable
    - sudo apt update
    - sudo {{ .INSTALLER }} install -y appimagelauncher
    status:
    - command -v AppImageLauncher